name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libgcrypt20-dev libgnutls28-dev gettext

    - name: autotools
      run: |
        make -f Makefile.cvs
        mkdir build

    - name: configure
      working-directory: build
      run: ../configure --with-guis=none

    - name: make
      working-directory: build
      run: make -j4

    - name: make check
      working-directory: build
      run: make check
